### ISSUE TITLE
Add multi platform build for Docker containers

### ISSUE THREAD

**Issue by lilachic** [CSCfi/docker-emscripten-crypt4gh#8]
Can we adjust pipeline to  build containers with both AMD64 (x86) and ARM64 architecture?  There is increasing amount of Macs with  M1/M2 ARM processor architecture where amd64 containers don't run natively. Github actions do support multi platform build .  An example from https://docs.docker.com/build/ci/github-actions/multi-platform/

```
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: user/app:latest
```

This to succeed the emskd should be first support multi architecture building, but the multi platform container image is not found in Docker hub, https://hub.docker.com/r/emscripten/emsdk.

emscripten/emsdk:latest (3.1.45) and emscripten/emsdk:3.1.41 have both "Architecture": "amd64" .

Other drawback is that building this image is highly resource consuming , with 8G RAM virtual machine it takes almost 2 hours of time.
